#!/bin/sh
bundle=$1
[ -n "$bundle" ] || exit 0

started=''
for input in "$@"; do
    if [ -z "$started" ]; then
        started="yes"
        continue
    fi
    inputdir=`dirname $input`
    name=`basename $inputdir`/`basename $input`
    plugin=$bundle/Contents/Plugins/$name
    echo "Copying $name"
    mkdir -p `dirname $plugin`
    cp $input $plugin
    for dep in `otool -L $plugin | grep '\t/' | grep -v /usr/lib | grep -v /System/Library | cut -d" " -f1`; do
        reldep=`echo $dep | sed -e 's/.*\/lib\///'`
        install_name_tool -change $dep @executable_path/../Frameworks/$reldep $plugin
    done
done
