#!/bin/sh -e
BUNDLE=
FRAMEWORKS=
IMPORTS=
PLUGINS=
QMAKE=

# parse arguments
args=`getopt b:f:i:p:q: $*`
set -- $args
for i; do
    case "$i" in
    -b) shift; BUNDLE=$1; shift;;
    -f) shift; FRAMEWORKS="$FRAMEWORKS $1"; shift;;
    -i) shift; IMPORTS="$IMPORTS $1"; shift;;
    -q) shift; QMAKE=$1; shift;;
    --) shift; break;;
    esac
done
PLUGINS=$*

if [ -z "$BUNDLE" ]; then
    echo "You need to specify bundle"
    exit 1
fi

# query qmake
if [ -z "$QMAKE" ]; then
    echo "You need to specify qmake"
    exit 1
fi
QT_INSTALL_LIBS=`$QMAKE -query QT_INSTALL_LIBS`
QT_INSTALL_IMPORTS=`$QMAKE -query QT_INSTALL_IMPORTS`
QT_INSTALL_PLUGINS=`$QMAKE -query QT_INSTALL_PLUGINS`
DEPLOY_LIBS=$BUNDLE/Contents/Frameworks
DEPLOY_IMPORTS=$BUNDLE/Contents/Imports
DEPLOY_PLUGINS=$BUNDLE/Contents/PlugIns
DEPLOY_RESOURCES=$BUNDLE/Contents/Resources

fix_deps() {
    dst=$1
    filter=`basename $dst`
    for dep in `otool -L $dst | grep -v $filter | grep -v /usr/lib | grep -v /System/Library | cut -d" " -f1`; do
        dep_name=`echo $dep | sed -e 's/.*\/lib\///'`
        dep_id="@executable_path/../Frameworks/$dep_name"
        install_name_tool -change $dep $dep_id $dst
        dep_inst="$DEPLOY_LIBS/$dep_name"
        if [ ! -e $dep_inst ]; then
            echo "Copying library $dep"
            mkdir -p `dirname $dep_inst`
            cp $dep $dep_inst
            install_name_tool -id $dep_id $dep_inst
        fi
    done
}

# copy Qt libraries
macdeployqt $BUNDLE -no-plugins

# generate Qt config file
mkdir -p $DEPLOY_RESOURCES
( echo "[Paths]"; echo "Plugins = PlugIns"; echo "Imports = Imports" ) > $DEPLOY_RESOURCES/qt.conf

# copy Qt resources
cp -R $QT_INSTALL_LIBS/Resources/qt_menu.nib $DEPLOY_RESOURCES/

# copy frameworks
for framework in $FRAMEWORKS; do
    src="/Library/Frameworks/$framework.framework"
    dst="$DEPLOY_LIBS/$framework.framework"
    echo "Copying framework $framework"
    rm -rf $dst
    cp -a $src $dst
done

# copy imports
mkdir -p $DEPLOY_IMPORTS
for import in $IMPORTS; do
    src=$QT_INSTALL_IMPORTS/$import
    dst=$DEPLOY_IMPORTS/$import
    echo "Copying import $import"
    rm -rf $dst
    cp -a $src $dst
    fix_deps $dst/*.dylib
done

# copy plugins
for name in $PLUGINS; do
    src=$QT_INSTALL_PLUGINS/$name
    dst=$DEPLOY_PLUGINS/$name
    echo "Copying plugin $name"
    mkdir -p `dirname $dst`
    cp $src $dst
    fix_deps $dst
done

# Strip QT Framework to keep only "i386" part in case of a universal binary
# (if QT was installed as a binary from qt.nokia.com, it contains both i386 and ppc parts. WiLink is only supported and tested for i386)
for framework in `find $DEPLOY_LIBS -type f -name 'Qt*'`; do
    if file "$framework" | grep -q "universal"; then
        lipo -thin i386 -output "$framework.thin" "$framework" && mv "$framework.thin" "$framework"
    fi
done
