#!/bin/sh -e

SELF=$0
DEPLOY_LIBS=$1
dst=$2
filter=`basename $dst`
for dep in `otool -L $dst | grep -v $filter | grep -v /usr/lib | grep -v @executable_path | grep -v /System/Library | cut -d" " -f1`; do
    dep_name=`echo $dep | sed -e 's/.*\/lib\///'`
    dep_id="@executable_path/../Frameworks/$dep_name"
    echo install_name_tool -change $dep $dep_id $dst
    install_name_tool -change $dep $dep_id $dst
    dep_inst="$DEPLOY_LIBS/$dep_name"
    if [ ! -e $dep_inst ]; then
        echo "Copying library $dep"
        mkdir -p `dirname $dep_inst`
        cp $dep $dep_inst
        echo install_name_tool -id $dep_id $dep_inst
        install_name_tool -id $dep_id $dep_inst
    fi

    $SELF $1 $dep_inst
done
