#!/usr/bin/env python

import binascii
import colorsys
import fileinput
import re
import sys

color_re = re.compile(r'#([0-9a-f]{6})')

def red_to_orange(r, g, b):
        rf, gf, bf = map(lambda x: x/float(255), (r, g, b))
        h, s, v = colorsys.rgb_to_hsv(rf, gf, bf)
        r, g, b = colorsys.hsv_to_rgb(h + 1.0/12.0, s, v + 1.0/12.0)
        return map(lambda x: int(min(x, 1) * 255), (r, g, b))

def red_to_green(r, g, b):
    return g, r, b

def red_to_gray(r, g, b):
    lum = int(0.3 * r + 0.59 * g + 0.11 * b)
    return lum, lum, lum

for line in fileinput.input():
    for col in color_re.findall(line):
        r, g, b = map(ord, binascii.unhexlify(col))
        r, g, b = red_to_orange(r, g, b)
        newcol = binascii.hexlify("".join(map(chr, (r, g, b))))
        line = line.replace(col, newcol)
    sys.stdout.write(line)
